name: torg_gitlab
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  torg_gitlab_uikit:
    path: local_libs/torg_gitlab_uikit
  http: ^0.12.0
  # rxdart: ^0.19.0
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  fonts:
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
    - family: MenloRegular
      fonts:
        - asset: assets/fonts/MenloRegular.ttf
