/// Flutter icons TorgGitlabIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TorgGitlabIcons
///      fonts:
///       - asset: fonts/TorgGitlabIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TorgGitlabIcons {
  TorgGitlabIcons._();

  static const _kFontFam = 'TorgGitlabIcons';

  static const IconData arrow_down = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData merge_requests = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData project = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData repository = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData file = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe805, fontFamily: _kFontFam);
}
